### ISSUE TITLE
Did you use reinforcement learning?

### ISSUE THREAD

**Issue by TriBall3** [columbia-ai-robotics/dextairity#1]
Hi!
I read your paper and saw the keywords about FIFO replay buffer in it. Did you use reinforcement learning when you trained Blowing NetWork?This article of FlingBot says that self-supervised learning is used, is reinforcement learning also used in training the Grasping Net?
Thanks for your reply !

**Comment by zhenjia-xu** [comment]
Thanks for your interest.
Both BlowNet and GraspNet are using self-supervised training, instead of reinforcement learning. To be more specific, the algorithm simultaneously collects data and trains both networks during the online training procedure, and FIFO replay buffer is used to store data for training.

**Comment by TriBall3** [comment]
Hi!
Are the datasets here automatically labeled or manually labeled?

**Comment by zhenjia-xu** [comment]
They are automatically labeled.
In the cloth unfolding task, the label is cloth coverage, which can be computed via background subtraction on a top-down image. In the bag opening task, the label is whether the bag is opened or not, which can be computed via background subtraction on a side-view image and comparison with a pre-defined threshold.
For more details, please refer to our paper.
